### ISSUE TITLE
Cannot install pypiwin32 dependency on Linux

### ISSUE THREAD

**Issue by matenestor** [jithurjacob/Windows-10-Toast-Notifications#109]
I have problems installing the **pypiwin32** dependency. 
Here is an error I got after `pip install pypiwin32` commad:

```bash
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
  Using cached pypiwin32-219.zip (4.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j05lwo34/pypiwin32_28c64a416f95418186ddbb47be04fe6a/setup.py", line 121
          print "Building pywin32", pywin32_version
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I don't understand why the wheel package version 223 downloads a version 219 of the zip archive. So next I tried specifying a version as it is suggested on Pypi, but also without success.

After `pip install pypiwin32==223` commad:

```bash
Collecting pypiwin32==223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
ERROR: Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32) (from versions: none)
ERROR: No matching distribution found for pywin32>=223
```

Using the `--no-cache-dir` has no effect. I am developing a small project on Linux, that will be used on Windows. Python packages should not be that critically influenced by an OS platform, when I want to just install them, right?

**Comment by pawelk1337** [comment]
This is **ONLY** for windows as suggested in the name you may now close the issue
