### ISSUE TITLE
Installation from pip does not work

### ISSUE THREAD

**Issue by florianluediger** [jithurjacob/Windows-10-Toast-Notifications#16]
Since you updated win10toast in the pip repository, installation does not work anymore for me. It looks like the requirements.txt file can not be found. For reference, this is the error:

```
PS C:\Python 361\VENVs\Test\Scripts> .\pip.exe install win10toast --no-cache-dir
Collecting win10toast
  Downloading win10toast-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Python 361\VENVs\Test\lib\site-packages\pip-9.0.1-py3.6.egg\pip\download.py", line 421, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\flori\\AppData\\Local\\Temp\\pip-build-u758glcl\\win10toast\\requirements.txt'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\flori\AppData\Local\Temp\pip-build-u758glcl\win10toast\setup.py", line 18, in <module>
        parse_requirements(from_here("requirements.txt"), session="")
      File "C:\Python 361\VENVs\Test\lib\site-packages\pip-9.0.1-py3.6.egg\pip\req\req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "C:\Python 361\VENVs\Test\lib\site-packages\pip-9.0.1-py3.6.egg\pip\download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'C:\\Users\\flori\\AppData\\Local\\Temp\\pip-build-u758glcl\\win10toast\\requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\flori\AppData\Local\Temp\pip-build-u758glcl\win10toast\
```

**Comment by punk609** [comment]
Same problem

**Comment by Dario0117** [comment]
What I did to fix it was install `pypiwin32` first, then i download the repository and modify `setup.py` and remove the requirements for installation, then I installed it manually with `setup.py install` and I was able to install it correctly.

**Comment by jithurjacob** [comment]
@punk609 @florianluediger  thank you for reporting the issue. I've fixed it by uploading the whl file.
