### ISSUE TITLE
Explorer.exe freezing when sending a notification

### ISSUE THREAD

**Issue by spider93287** [jithurjacob/Windows-10-Toast-Notifications#17]
## Windows 10 Version

Windows 10 Build - 14393.1198

## Error Code
```
>>> toaster.show_toast("Hello World!", "Python!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\win10toast\__init__.py", line 123, in show_toast
    UnregisterClass(self.wc.lpszClassName, None)
pywintypes.error: (1412, 'UnregisterClass', 'Class still has open windows.')
```

## Description

After toaster.show_toast was run, the Windows 10 taskbar freezes. Task Manager was required to restart Explorer.exe.

**Comment by spider93287** [comment]
I've restarted Windows, and it's started working now...
