### ISSUE TITLE
Issues with python wrapper

### ISSUE THREAD

**Issue by Bluscream** [jithurjacob/Windows-10-Toast-Notifications#28]
Hello, i wonder if you're still maintaining and keeping an eye on this, if so please respond so i don't waste my time explaining my problem to a wall :)

**Comment by jithurjacob** [comment]
Closing this as I don't have to waste my  "time"  reading your problem.

**Comment by Bluscream** [comment]
Sorry, the wording was kinda bad, but i'm not a native english speaker so please forgive me. I just had the experience a few times that i've spent > an hour to explain my problem to a dead repo/account

**Comment by Bluscream** [comment]
So i'm actually trying to use your lib in https://github.com/pathmann/pyTSon which is a custom C->python wrapper. the problem is that i can't get the toasts to work even tho i installed `pypiwin32`.

```
2/18/2018 03:22:38	pyTSon.PluginHost.reload	Error	Error loading python plugin from C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon\scripts\friendNotifications\: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 322, in reload
    cls.modules[base] = importlib.__import__(base)
  File "<frozen importlib._bootstrap>", line 1055, in __import__
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\friendNotifications\__init__.py", line 4, in <module>
    from win10toast import ToastNotifier
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\win10toast\__init__.py", line 19, in <module>
    from win32api import GetModuleHandle
ImportError: No module named 'win32api'
```

If you require more infos to understand it please tell me :)

**Comment by jithurjacob** [comment]
Are you able to import win32api separately?

**Comment by Bluscream** [comment]
by just adding an `import win32api` to **which** file?

here's a overview of the installed packages after installing `win10toast`
![grafik](https://user-images.githubusercontent.com/3318223/36359161-60cb204c-1518-11e8-9b42-48c94f7d92cc.png)

**Comment by jithurjacob** [comment]
I'm not familiar with PyTSon. Can you please open a new python cli in shell/cmd and try "import win32api"

**Comment by Bluscream** [comment]
Like this? 

![](https://i.imgur.com/Evt0rxo.png)

or this?

![](https://i.imgur.com/IRaVq7i.png)

**Comment by jithurjacob** [comment]
Second way. 

Can you please try "pip install pypiwin32"

**Comment by Bluscream** [comment]
![](https://i.imgur.com/FsrOyLR.png)

**Comment by jithurjacob** [comment]
Is PyTSon using different Python installation? 

Please open a new cmd and try the sample code given readme.

**Comment by Bluscream** [comment]
Your readme or pywin32's ?

**Comment by jithurjacob** [comment]
Mine

**Comment by harmanvishnoi** [comment]
![_2018-02-27_15-37-07](https://user-images.githubusercontent.com/7094042/36722687-35092f72-1bd4-11e8-86c2-b6ec7f6d4552.png)

Notification is appearing like this .not showing content. clicking on it does nothing.
(I have Win10)

**Comment by Bluscream** [comment]
Sorry for not trying thus so far. Gonna do it today

**Comment by micropicostack** [comment]
@harmanvishnoi I had the same issue, but it was solved by allowing _'Notifications'_ under _'System->Notifications & actions'_

Should this be added to the readme as prerequisite?
