### ISSUE TITLE
ClassAtom missing

### ISSUE THREAD

**Issue by manavrawat10** [jithurjacob/Windows-10-Toast-Notifications#33]
'ToastNotifier' object has no attribute 'classAtom'

**Comment by ilyamikcoder** [comment]
Try to close and open python

**Comment by kms70847** [comment]
At least one other person has had this problem: https://stackoverflow.com/questions/50741455/toastnotifier-object-has-no-attribute-classatom

This appears to occur when the initial assignment of `classAtom` fails at https://github.com/jithurjacob/Windows-10-Toast-Notifications/blob/master/win10toast/__init__.py#L78. Since the except block does nothing but pass, we don't know any details about the error that RegisterClass is throwing. It might be nice to remove the try and except. It wouldn't solve the underlying problem, but it would make it easier to diagnose.

**Comment by Dobad** [comment]
Run into the same promlem. Here's the detailed exception:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\win10toast\__init__.py", line 83, in _show_toast
    self.hwnd = CreateWindow(self.classAtom, "Taskbar", style,
AttributeError: 'ToastNotifier' object has no attribute 'classAtom'
```

**Comment by jieggii** [comment]
The problem happens when you try to display more than one notification. I've made a gist that solves the problem displaying them one by one, but I don't think that it is the best way to do this.

**Comment by akeeman** [comment]
In my case I lazily was creating a ` ToastNotifier` instance for each notification. Then `RegisterClass` tells me that the registration has already been done, so it can't register again. So just make sure you create only  a single instance of `ToastNotifier`.

**Comment by badjano** [comment]
Thanks @akeeman, I was also doing that!
Maybe changing the modus operandi to something like a singleton might protect other people from making the same mistake
